store state faster and stop on errors
redpencilio/ldes-consumer-service pull request #33
Opened 2023-03-02 15:10 UTC by nvdk

initially just wanted better state management (storing state faster and stopping on errors), ended up refactoring a bit. no longer uses the ldes-consumer library now.

The consumeStream method uses an async promise executor which is considered a bad pattern, but I think I've handled possible errors and don't really see a better way of writing this at the moment.

2023-03-02 15:21 UTC, nvdk commented on consumer.ts
> +      disableSynchronization: false
whoops this should be true, we don't expect the service to keep running when it's done

2023-03-02 15:50 UTC, nvdk commented
Tested on two feeds:
- https://ipdc.vlaanderen.be/id/conceptsnapshot?pageNumber=0 (finishes without error)
- https://marineregions.org/feed stops on error

2023-03-09 15:59 UTC, nvdk commented on consumer.ts
> +      const lastState = await fetchState(this.datasetIri);
should probably add a `.catch((e) => reject(e)` here

2023-03-10 11:11 UTC, elpoelma commented on consumer.ts
> +enum PAUZE_REASONS {
This should probably be pause :)

2023-03-13 13:57 UTC, elpoelma reviewed
It seems to work well in combination with the ipdc LDES feed.

2023-03-13 14:14 UTC, elpoelma requested changes
Seems to work well overall. I did notice that the service hangs up when the endpoint URL is malformed.

2023-03-26 14:32 UTC, MPParsley commented
"@treecg/actor-init-ldes-client": "https://github.com/redpencilio/event-stream-client/releases/download/actor-init-ldes-client-v3.0.0-fix-pausing/treecg-actor-init-ldes-client-3.0.0.tgz",

cases a

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@treecg/actor-init-ldes-client'
Require stack:
- /usr/src/build/consumer.js
- /usr/src/build/app.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/src/build/consumer.js:7:28)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/build/consumer.js', '/usr/src/build/app.js' ]
}
```

2023-04-01 08:44 UTC, MPParsley requested changes

2023-04-01 08:44 UTC, MPParsley commented on app.ts
> -            process.exit();
This breaks the RUNONCE option.

2023-05-17 10:01 UTC, nvdk commented
closing in favour of #36

2023-05-17 10:01 UTC, closed without merging